# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='com.casi.pb',
  serialized_pb='\n\rservice.proto\x12\x0b\x63om.casi.pb\"R\n\x04User\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12#\n\x06gender\x18\x04 \x02(\x0e\x32\x13.com.casi.pb.Gender*\x1e\n\x06Gender\x12\x08\n\x04MALE\x10\x01\x12\n\n\x06\x46\x45MALE\x10\x00\x32w\n\rUserOperation\x12\x31\n\tgetUserID\x12\x11.com.casi.pb.User\x1a\x11.com.casi.pb.User\x12\x33\n\x0bgetUserName\x12\x11.com.casi.pb.User\x1a\x11.com.casi.pb.UserB\x03\x90\x01\x01')

_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='com.casi.pb.Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MALE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=1, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=114,
  serialized_end=144,
)

Gender = enum_type_wrapper.EnumTypeWrapper(_GENDER)
MALE = 1
FEMALE = 0



_USER = _descriptor.Descriptor(
  name='User',
  full_name='com.casi.pb.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.casi.pb.User.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.casi.pb.User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='com.casi.pb.User.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='com.casi.pb.User.gender', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=112,
)

_USER.fields_by_name['gender'].enum_type = _GENDER
DESCRIPTOR.message_types_by_name['User'] = _USER

class User(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USER

  # @@protoc_insertion_point(class_scope:com.casi.pb.User)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_USEROPERATION = _descriptor.ServiceDescriptor(
  name='UserOperation',
  full_name='com.casi.pb.UserOperation',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=146,
  serialized_end=265,
  methods=[
  _descriptor.MethodDescriptor(
    name='getUserID',
    full_name='com.casi.pb.UserOperation.getUserID',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_USER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getUserName',
    full_name='com.casi.pb.UserOperation.getUserName',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_USER,
    options=None,
  ),
])

class UserOperation(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _USEROPERATION
class UserOperation_Stub(UserOperation):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _USEROPERATION

# @@protoc_insertion_point(module_scope)
